sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_c4697db24c30_key -iv $encrypted_c4697db24c30_iv -in key.json.enc -out key.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set project multi-k8s-236811 
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t photon628/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run photon628/react-test npm test -- --coverage
  
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master