sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_c4697db24c30_key -iv $encrypted_c4697db24c30_iv -in key.json.enc -out key.json -d
  - curl https://sdk.cloud.google.com | bash > dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  