apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: milhamh-k8s--com-tls
spec:
  secretName: milhamh-k8s-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: milhamh-k8s.com
  dnsNames:
    - milhamh-k8s.com
    - www.milhamh-k8s.com
  acem:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - milhamh-k8s.com
          - www.milhamh-k8s.com